export { WidgetCard, WidgetStat, WidgetRow, WidgetDivider } from './WidgetCard'
export { PracticeSummaryWidget } from './PracticeSummaryWidget'
export { StaffResourcingWidget } from './StaffResourcingWidget'
export { FinancialHealthWidget } from './FinancialHealthWidget'
export { QuoteInvoiceWidget } from './QuoteInvoiceWidget'
export { JobsAtRiskWidget } from './JobsAtRiskWidget'
export { CalendarDeadlinesWidget } from './CalendarDeadlinesWidget'
export { ProjectUpdatesWidget } from './ProjectUpdatesWidget'
export { BRPDWidget } from './BRPDWidget'
export { NewsWidget } from './NewsWidget'
export { RecentActivityWidget } from './RecentActivityWidget'
