import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { withAuth } from '@/lib/with-auth'
import { ValidationError, NotFoundError } from '@/lib/errors'
import PDFDocument from 'pdfkit'

/* ── Colours ───────────────────────────────────────────── */

const BRAND = '#18181b'
const ACCENT = '#2563eb'
const MUTED = '#71717a'
const BORDER = '#e4e4e7'
const TABLE_HEAD_BG = '#f4f4f5'

/* ── Helpers ───────────────────────────────────────────── */

function fmtDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-GB', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
  })
}

const PRIORITY_LABELS: Record<string, string> = {
  CRITICAL: 'Critical',
  HIGH: 'High',
  MEDIUM: 'Medium',
  LOW: 'Low',
}

const STATUS_LABELS: Record<string, string> = {
  NOT_STARTED: 'Not started',
  IN_PROGRESS: 'In progress',
  BLOCKED: 'Blocked',
  READY_FOR_REVIEW: 'In review',
  CHANGES_REQUIRED: 'Changes needed',
  COMPLETED: 'Completed',
}

/* ── PDF Generator ─────────────────────────────────────── */

interface TaskRow {
  taskNumber: string
  title: string
  status: string
  priority: string
  ownerName: string
  dueDate: string | null
}

async function generateTaskListPdf(
  organisationName: string,
  projectName: string,
  projectCode: string | null,
  tasks: TaskRow[],
  generatedBy: string,
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = []
    const doc = new PDFDocument({
      size: 'A4',
      layout: 'landscape',
      margins: { top: 50, bottom: 60, left: 50, right: 50 },
      info: {
        Title: `Tasks — ${projectName}`,
        Author: organisationName,
        Subject: 'Task List Export',
        Creator: 'Coordin.io',
      },
      bufferPages: true,
    })

    doc.on('data', (chunk: Buffer) => chunks.push(chunk))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    const pageW = 841.89 // A4 landscape
    const contentW = pageW - 100
    let y = 50

    /* ── Header ─────────────────────────────────────── */

    doc
      .font('Helvetica-Bold')
      .fontSize(18)
      .fillColor(BRAND)
      .text(organisationName, 50, y)

    doc
      .font('Helvetica')
      .fontSize(9)
      .fillColor(MUTED)
      .text(fmtDate(new Date().toISOString()), 50, y, { width: contentW, align: 'right' })

    y += 30

    // Accent line
    doc
      .moveTo(50, y)
      .lineTo(pageW - 50, y)
      .strokeColor(ACCENT)
      .lineWidth(2)
      .stroke()

    y += 14

    /* ── Title + summary ────────────────────────────── */

    doc
      .font('Helvetica-Bold')
      .fontSize(14)
      .fillColor(BRAND)
      .text(`Task List — ${projectName}`, 50, y)

    y += 20

    doc
      .font('Helvetica')
      .fontSize(9)
      .fillColor(MUTED)
      .text(`${tasks.length} task${tasks.length === 1 ? '' : 's'} · Generated by ${generatedBy}`, 50, y)

    y += 20

    /* ── Table ──────────────────────────────────────── */

    const cols = {
      num:      { x: 50,  w: 70 },
      title:    { x: 120, w: 280 },
      status:   { x: 400, w: 100 },
      priority: { x: 500, w: 70 },
      owner:    { x: 570, w: 120 },
      due:      { x: 690, w: 100 },
    }
    const tableRight = cols.due.x + cols.due.w
    const rowH = 22

    // Table header
    doc
      .rect(50, y, tableRight - 50, rowH)
      .fill(TABLE_HEAD_BG)

    doc.font('Helvetica-Bold').fontSize(8).fillColor(MUTED)
    doc.text('ID', cols.num.x + 4, y + 7, { width: cols.num.w, align: 'left' })
    doc.text('Title', cols.title.x + 4, y + 7, { width: cols.title.w, align: 'left' })
    doc.text('Status', cols.status.x + 4, y + 7, { width: cols.status.w, align: 'left' })
    doc.text('Priority', cols.priority.x + 4, y + 7, { width: cols.priority.w, align: 'left' })
    doc.text('Owner', cols.owner.x + 4, y + 7, { width: cols.owner.w, align: 'left' })
    doc.text('Due Date', cols.due.x + 4, y + 7, { width: cols.due.w, align: 'left' })

    y += rowH

    // Rows
    tasks.forEach((task, idx) => {
      // Page break check (landscape page height ~545 usable)
      if (y + rowH > 530) {
        doc.addPage()
        y = 50
      }

      // Alternating row background
      if (idx % 2 === 1) {
        doc.rect(50, y, tableRight - 50, rowH).fill('#fafafa')
      }

      // Row border
      doc.moveTo(50, y + rowH).lineTo(tableRight, y + rowH).strokeColor(BORDER).lineWidth(0.5).stroke()

      doc.font('Helvetica').fontSize(8).fillColor(MUTED)
      doc.text(task.taskNumber, cols.num.x + 4, y + 7, { width: cols.num.w - 8, align: 'left' })

      doc.font('Helvetica').fontSize(8).fillColor(BRAND)
      doc.text(task.title, cols.title.x + 4, y + 7, { width: cols.title.w - 8, align: 'left', ellipsis: true })

      doc.font('Helvetica').fontSize(8).fillColor(MUTED)
      doc.text(STATUS_LABELS[task.status] || task.status, cols.status.x + 4, y + 7, { width: cols.status.w - 8, align: 'left' })

      doc.font('Helvetica').fontSize(8).fillColor(MUTED)
      doc.text(PRIORITY_LABELS[task.priority] || task.priority, cols.priority.x + 4, y + 7, { width: cols.priority.w - 8, align: 'left' })

      doc.font('Helvetica').fontSize(8).fillColor(MUTED)
      doc.text(task.ownerName, cols.owner.x + 4, y + 7, { width: cols.owner.w - 8, align: 'left', ellipsis: true })

      doc.font('Helvetica').fontSize(8).fillColor(MUTED)
      doc.text(task.dueDate ? fmtDate(task.dueDate) : '—', cols.due.x + 4, y + 7, { width: cols.due.w - 8, align: 'left' })

      y += rowH
    })

    /* ── Footer on every page ──────────────────────── */

    const pageCount = doc.bufferedPageRange().count
    for (let i = 0; i < pageCount; i++) {
      doc.switchToPage(i)

      const footerY = 555
      doc.moveTo(50, footerY).lineTo(pageW - 50, footerY).strokeColor(BORDER).lineWidth(0.5).stroke()

      doc
        .font('Helvetica')
        .fontSize(7)
        .fillColor(MUTED)
        .text(
          `${projectCode || 'Tasks'} — Generated by Coordin.io`,
          50,
          footerY + 6,
          { width: contentW / 2, align: 'left' },
        )

      doc
        .font('Helvetica')
        .fontSize(7)
        .fillColor(MUTED)
        .text(
          `Page ${i + 1} of ${pageCount}`,
          pageW / 2,
          footerY + 6,
          { width: contentW / 2, align: 'right' },
        )
    }

    doc.end()
  })
}

/* ── Route Handler ─────────────────────────────────────── */

/**
 * GET /api/tasks/export-pdf?projectId=xxx[&status=...][&priority=...][&ownerId=...]
 *
 * Generate and download a PDF of the task list for a project.
 * Requires at least MEMBER permission.
 */
export const GET = withAuth(async (request: NextRequest, { profile }) => {
  const url = new URL(request.url)
  const projectId = url.searchParams.get('projectId')

  if (!projectId) {
    throw new ValidationError('projectId is required')
  }

  // Verify the project belongs to the user's organisation
  const project = await prisma.project.findUnique({
    where: { id: projectId },
    select: { id: true, name: true, code: true, organisationId: true },
  })

  if (!project || project.organisationId !== profile.organisationId) {
    throw new NotFoundError('Project not found')
  }

  // Build filter conditions
  const where: Record<string, unknown> = {
    projectId,
    archivedAt: null,
  }

  const statusParam = url.searchParams.get('status')
  if (statusParam) {
    where.status = statusParam
  }

  const priorityParam = url.searchParams.get('priority')
  if (priorityParam) {
    where.priority = priorityParam
  }

  const ownerIdParam = url.searchParams.get('ownerId')
  if (ownerIdParam) {
    where.ownerId = ownerIdParam
  }

  // Fetch tasks + numbering data
  const [allTaskIds, tasks] = await Promise.all([
    prisma.task.findMany({
      where: { projectId },
      select: { id: true },
      orderBy: [{ createdAt: 'asc' }, { id: 'asc' }],
    }),
    prisma.task.findMany({
      where,
      include: {
        owner: { select: { id: true, fullName: true } },
      },
      orderBy: [
        { priority: 'desc' },
        { dueDate: 'asc' },
      ],
    }),
  ])

  const numberMap = new Map(allTaskIds.map((t, i) => [t.id, i + 1]))
  const prefix = project.code || 'T'

  const taskRows: TaskRow[] = tasks.map((t) => ({
    taskNumber: `${prefix}-${String(numberMap.get(t.id) || 0).padStart(3, '0')}`,
    title: t.title,
    status: t.status,
    priority: t.priority,
    ownerName: t.owner?.fullName || 'Unassigned',
    dueDate: t.dueDate?.toISOString() ?? null,
  }))

  const pdfBuffer = await generateTaskListPdf(
    profile.organisation.name,
    project.name,
    project.code,
    taskRows,
    profile.fullName,
  )
  const uint8 = new Uint8Array(pdfBuffer)

  const filename = `tasks-${(project.code || project.name).replace(/[^a-zA-Z0-9-]/g, '_')}-${new Date().toISOString().slice(0, 10)}.pdf`

  return new NextResponse(uint8, {
    status: 200,
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${filename}"`,
      'Content-Length': String(pdfBuffer.length),
      'Cache-Control': 'no-store',
    },
  })
})
